name: build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install Babel
        run: npm install @babel/core @babel/preset-env

      - name: Run tests with Babel
        run: |
          npm test
        env:
          BABEL_ENV: test
